# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
plugins:
- autoresize
# - fullscreen
# - contextmenu
# - directionality
# - emotions
# - example
# - inlinepopups
# - layer
# - legacyoutput
# - nonbreaking
# - preview
# - style
# - tabfocus
# - template
# - wordcount
# - xhtmlxtras
# - table
